# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5478069bc2d7e9fd542ac5812a375df6228c03ae4c3c7dbfd07a9377516c6380e8e350d908454d5f765ed932beae079d1eda0db6525b0e8a2f22bdbbc8dc48a7

test:
  secret_key_base: 36af0d818acb6bae00ff2e470df03d03685ee4e3159d16ae5d4d5c58c0bb94e52b9a41486a9e63560b871ce6527c9984da3023c8d741589e2a34fe23fe256521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
